### ISSUE TITLE
Cannot sign objects in the new frankfurt region?

### ISSUE THREAD

**Issue by gCurtisCT** [maxnachlinger/cloudfront-private-url-creator#6]
When trying to access signed objects from the new Frankfurt region, I get this:

"The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256."

From the [AWS blog post] (http://aws.amazon.com/blogs/aws/aws-region-germany/):
"This new Region supports only [Signature Version 4](http://docs.aws.amazon.com/general/latest/gr/signature-version-4.html)"

**Comment by gCurtisCT** [comment]
Any updates?

**Comment by maxnachlinger** [comment]
Nope, Amazon still has a bug, see: https://forums.aws.amazon.com/thread.jspa?messageID=580347

**Comment by maxnachlinger** [comment]
Looks like Amazon fixed the issue. The docs claim that no changes are needed for signing Cloudfront urls (relevant doc is here: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html#private-content-origin-access-identity-signature-version-4). Please test this, and if it still doesn't work I'll dig into it.

**Comment by gCurtisCT** [comment]
Yep, I tested it and it works fine.
